-- 01. 주요 시/도의 연령대별 인구수 합계 구하기
SELECT * FROM TB_POPLTN;

SELECT A.AGRDE_SE_CD, SUM(A.POPLTN_CNT) AGRDE_POPLTN_DNT
FROM TB_POPLTN A
WHERE A.ADMINIST_ZONE_NO LIKE '__00000000' -- 어차피 시/도 코드는 아ㅍ의 2자리가 다리고, 나머지 8자리는 0
  AND A.STD_MT = '202304'
  AND A.POPLTN_SE_CD = 'T'
GROUP BY A.AGRDE_SE_CD
ORDER BY A.AGRDE_SE_CD;

-- 02. 2023년 4월 ㅣ준 전국 주요 시/도의 연령대별 인구수 합계, 연령대별 인구 비율 구하기
-- 내답
SELECT A.AGRDE_SE_CD, SUM(A.POPLTN_CNT) AGRDE_POPLTN_DNT, ROUND(SUM(A.POPLTN_CNT)/(SELECT SUM(POPLTN_CNT)
																				   FROM TB_POPLTN A
																				   WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
																					 AND A.STD_MT = '202304'
																					 AND A.POPLTN_SE_CD = 'T') * 100, 2) 인구비율
FROM TB_POPLTN A
WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
  AND A.STD_MT = '202304'
  AND A.POPLTN_SE_CD = 'T'
GROUP BY A.AGRDE_SE_CD
ORDER BY A.AGRDE_SE_CD;

-- 강사님 답
SELECT C.AGRDE_SE_CD,
		C.AGRDE_POPLTN_CNT,
        ROUND((C.AGRDE_POPLTN_CNT/C.SUM_AGRDE_POPLTN_CNT) * 100, 2) AS "인구비율"
FROM (
		SELECT
			B.AGRDE_SE_CD,
			B.AGRDE_POPLTN_CNT,
			SUM(B.AGRDE_POPLTN_CNT) OVER() AS SUM_AGRDE_POPLTN_CNT -- WINDOW FUNCTION
		FROM(
				SELECT A.AGRDE_SE_CD, SUM(A.POPLTN_CNT) AGRDE_POPLTN_CNT
				FROM TB_POPLTN A
				WHERE A.ADMINIST_ZONE_NO LIKE '__00000000' -- 어차피 시/도 코드는 아ㅍ의 2자리가 다리고, 나머지 8자리는 0
					AND A.STD_MT = '202304'
					AND A.POPLTN_SE_CD = 'T'
				GROUP BY A.AGRDE_SE_CD
				ORDER BY A.AGRDE_SE_CD
			) B
	 ) C;


-- 03. 2023년 04월 기준 전국의 성별 인구수 합계를 구하고, 남성 / 여성 비율 구하기
	-- 남자 인구수, 연자 인구수, 남자 : 여자 비율(남자 인구 / 여자 인구), 남자 비율(남자 / 전체), 여자 비율(여자 / 전체)
	-- OVER() 안써도 됨. CASE WHEN THEN 사용할 것. MAX 사용함.
SELECT * FROM TB_POPLTN;

-- 내답
SELECT POPLTN_SE_CD, CASE
					  WHEN POPLTN_SE_CD = 'M' THEN (SELECT SUM(POPLTN_CNT)
												   FROM TB_POPLTN
												   WHERE STD_MT = '202304' AND POPLTN_SE_CD = 'M' AND ADMINIST_ZONE_NO LIKE '__00000000'
												   GROUP BY POPLTN_SE_CD) / (SELECT SUM(POPLTN_CNT)
																			 FROM TB_POPLTN
																			 WHERE STD_MT = '202304' AND ADMINIST_ZONE_NO LIKE '__00000000' AND POPLTN_SE_CD IN ('M','F'))
					  WHEN POPLTN_SE_CD = 'F' THEN (SELECT SUM(POPLTN_CNT)
												   FROM TB_POPLTN
												   WHERE STD_MT = '202304' AND POPLTN_SE_CD = 'F' AND ADMINIST_ZONE_NO LIKE '__00000000'
												   GROUP BY POPLTN_SE_CD) / (SELECT SUM(POPLTN_CNT)
																			 FROM TB_POPLTN
																			 WHERE STD_MT = '202304' AND ADMINIST_ZONE_NO LIKE '__00000000'AND POPLTN_SE_CD IN ('M','F'))
					  ELSE (SELECT SUM(POPLTN_CNT)
							FROM TB_POPLTN
							WHERE STD_MT = '202304' AND POPLTN_SE_CD = 'M' AND ADMINIST_ZONE_NO LIKE '__00000000'
							GROUP BY POPLTN_SE_CD) / (SELECT SUM(POPLTN_CNT)
													   FROM TB_POPLTN
													   WHERE STD_MT = '202304' AND POPLTN_SE_CD = 'F' AND ADMINIST_ZONE_NO LIKE '__00000000'
													   GROUP BY POPLTN_SE_CD)
					END 인구
FROM TB_POPLTN
WHERE ADMINIST_ZONE_NO LIKE '__00000000'
	-- AND POPLTN_SE_CD IN ('M','F')
    AND STD_MT = '202304'
GROUP BY POPLTN_SE_CD;

-- 강사님답
SELECT * FROM TB_POPLTN WHERE ADMINIST_ZONE_NO LIKE '__00000000';

SELECT
	C.MALE_POPLTN_CNT,
    C.FEMALE_POPLTN_CNT,
    C.MALE_POPLTN_CNT / C.FEMALE_POPLTN_CNT AS "남성 / 여성 비율",
    C.MALE_POPLTN_CNT / (C.MALE_POPLTN_CNT + FEMALE_POPLTN_CNT) AS "전체 인구 대비 남성 비율",
    C.FEMALE_POPLTN_CNT / (C.MALE_POPLTN_CNT + C.FEMALE_POPLTN_CNT) AS "전체 인구 대비 여성 비율"
FROM(
		SELECT
			MAX(B.MALE_POPLTN_CNT) AS MALE_POPLTN_CNT,
			MAX(B.FEMAL_POPLTN_CNT) AS FEMALE_POPLTN_CNT
		FROM(
				SELECT A.POPLTN_SE_CD,
					  CASE WHEN A.POPLTN_SE_CD = 'M' THEN SUM(A.POPLTN_CNT) ELSE 0 END MALE_POPLTN_CNT,
					  CASE WHEN A.POPLTN_SE_CD = 'F' THEN SUM(A.POPLTN_CNT) ELSE 0 END FEMAL_POPLTN_CNT
				FROM TB_POPLTN A
				WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
					AND A.POPLTN_SE_CD IN ('M','F')
					AND A.STD_MT = '202304'
				GROUP BY A.POPLTN_SE_CD
				ORDER BY A.POPLTN_SE_CD
			) B
	 ) C;
     
-- 04. 연령대 별 인구가 가장 많은 지역 구하기
	-- 2023년 04월 기준 전국의 읍/면/동의 인구수(남 + 여)를 조회
-- 내풀이
SELECT 
	A.AGRDE_SE_CD,
    A.ADMINIST_ZONE_NO,
    A.ADMINIST_ZONE_NM,
    A.POPLTN_CNT
FROM TB_POPLTN A JOIN (SELECT
							AGRDE_SE_CD,
							MAX(POPLTN_CNT) MAX_POPLTN_CNT
						FROM TB_POPLTN 
						WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000'
							AND POPLTN_SE_CD = 'T'
							AND POPLTN_CNT > 0
							AND STD_MT = '202304'
						GROUP BY AGRDE_SE_CD) B ON A.AGRDE_SE_CD = B.AGRDE_SE_CD AND A.POPLTN_CNT = B.MAX_POPLTN_CNT
WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000'
	AND POPLTN_SE_CD = 'T'
	AND POPLTN_CNT > 0
	AND STD_MT = '202304'
ORDER BY AGRDE_SE_CD DESC;

-- 강사님 풀이
SELECT
	C.AGRDE_SE_CD,
	C.ADMINIST_ZONE_NO,
	C.ADMINIST_ZONE_NM,
	C.POPLTN_CNT
FROM(
	SELECT
		B.AGRDE_SE_CD,
		B.ADMINIST_ZONE_NO,
		B.ADMINIST_ZONE_NM,
		B.POPLTN_CNT,
		ROW_NUMBER() OVER(PARTITION BY B.AGRDE_SE_CD ORDER BY B.POPLTN_CNT DESC) AS RNUM -- 행번호 / PARTITION BY:파티션 / PARTITION BY : N개의 DATA에 대해 그룹생성 -> 정렬도 가능함 , 왜ㅐ N개냐면 OVER떄문에
	FROM(
		SELECT
			A.AGRDE_SE_CD,
			A.ADMINIST_ZONE_NO,
			A.ADMINIST_ZONE_NM,
			A.POPLTN_CNT
		FROM TB_POPLTN A
		WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
			AND A.POPLTN_SE_CD = 'T'
			AND A.POPLTN_CNT > 0
			AND A.STD_MT = '202304'
		ORDER BY POPLTN_CNT DESC
		) B
	) C
WHERE C.RNUM = 1 -- 각 파티션별 랭킹 1위만 가져오기
ORDER BY C.AGRDE_SE_CD;

-- 1) 연령대별 인구비율이 가장 높은 지역 구하기
	-- 2023년 04월 기준 전국의 각 지역의 연령대별 인구수 비율이 높은 지역을 찾는다. => GROUP BY를 쓸 수 없다. 하지만 그룹핑이 필요함(연령대별) 그럴때 OVER(PARTITION BY ~ )임
	-- POPLTN_CNT / SUM(POPLTN_CNT) OVER(PARTITION BY ADMINIST_ZONE_NO)
	-- 성별 코드가 'T'인 데이터 대상으로.
	-- ADMINIST_ZONE_NO NOT LIKE '_____00000'

SELECT C.AGRDE_SE_CD, C.ADMINIST_ZONE_NO, C.ADMINIST_ZONE_NM, C.POPLTN_CNT, C.행정구역별연령대의인구비율, C.RNK
FROM
	(
		SELECT B.AGRDE_SE_CD, B.ADMINIST_ZONE_NO, B.ADMINIST_ZONE_NM, B.POPLTN_CNT, B.행정구역별연령대의인구비율, 
			   ROW_NUMBER() OVER(partition by B.AGRDE_SE_CD ORDER BY B.행정구역별연령대의인구비율 DESC) RNK
		FROM
			(
				SELECT A.AGRDE_SE_CD, A.ADMINIST_ZONE_NO, A.ADMINIST_ZONE_NM, A.POPLTN_CNT, 
					   A.POPLTN_CNT / SUM(A.POPLTN_CNT) OVER(PARTITION BY A.ADMINIST_ZONE_NO) AS '행정구역별연령대의인구비율'
				FROM
					(
						SELECT AGRDE_SE_CD, ADMINIST_ZONE_NO, ADMINIST_ZONE_NM, POPLTN_CNT
						FROM TB_POPLTN
						WHERE 
								STD_MT = '202304' 
							AND POPLTN_SE_CD = 'T' 
							AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
					)A
			)B
	)C
WHERE C.RNK = 1
;


-- 2) 남성보다 여성의 수가 가장 많은 지역 구하기
	-- 전국의 각 읍/면/동 기준 남성의 수보다 여성의 수가 가장 많은 지역을 구한다.
	-- 여성인구수 - 남성인구수
SELECT ADMINIST_ZONE_NM, MAX(A.MALE_SUM), MAX(A.FEMALE_SUM), (MAX(A.FEMALE_SUM) - MAX(A.MALE_SUM)) CHA
FROM (
		SELECT ADMINIST_ZONE_NM, CASE
									WHEN POPLTN_SE_CD = 'M' THEN SUM(POPLTN_CNT) END MALE_SUM,
								CASE
									WHEN POPLTN_SE_CD = 'F' THEN SUM(POPLTN_CNT) END FEMALE_SUM
		FROM TB_POPLTN
		WHERE POPLTN_SE_CD IN ('F','M') AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
		GROUP BY ADMINIST_ZONE_NM, POPLTN_SE_CD
	  ) A
GROUP BY ADMINIST_ZONE_NM
ORDER BY CHA DESC LIMIT 1;

SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO, FEMALE_POPLTN_CNT - MALE_POPLTN_CNT AS CHA
FROM
	(
		SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO, MAX(MALE_POPLTN_CNT) MALE_POPLTN_CNT, MAX(FEMALE_POPLTN_CNT) FEMALE_POPLTN_CNT
		FROM
			(
				SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO,
					   CASE WHEN POPLTN_SE_CD = 'M' THEN POPLTN_CNT ELSE 0 END MALE_POPLTN_CNT,
					   CASE WHEN POPLTN_SE_CD = 'F' THEN POPLTN_CNT ELSE 0 END FEMALE_POPLTN_CNT
				FROM
					(
						SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO, POPLTN_SE_CD, SUM(POPLTN_CNT) AS POPLTN_CNT
						FROM TB_POPLTN
						WHERE POPLTN_SE_CD IN ('F','M') AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
						GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM, POPLTN_SE_CD
					)A
			)B
		GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM
	)C
ORDER BY FEMALE_POPLTN_CNT - MALE_POPLTN_CNT DESC
LIMIT 1
;

-- 3) 남성/여성 비율이 가장 높은 지역과 가장 낮은 지역 구하기
	-- 전국의 각 읍/면/동 기준 남성 비율 및 여성 비율이 가장 높거나 낮은 지역 구하기.
use basic_query;
SELECT *, CASE WHEN WOMAN_BE == MAX(WOMAN_BE) THEN 1 ELSE 0 END AS WRNK,
		  CASE WHEN MAN_BE == MAX(MAN_BE) THEN 1 ELSE 0 END AS MRNK
FROM (
		SELECT ADMINIST_ZONE_NM, 
				MAX(A.MALE_SUM) / (MAX(A.MALE_SUM)+MAX(A.FEMALE_SUM)) MAN_BE, 
				MAX(A.FEMALE_SUM) / (MAX(A.MALE_SUM)+MAX(A.FEMALE_SUM)) WOMAN_BE
		FROM (
				SELECT ADMINIST_ZONE_NM, CASE
											WHEN POPLTN_SE_CD = 'M' THEN SUM(POPLTN_CNT) END MALE_SUM,
										CASE
											WHEN POPLTN_SE_CD = 'F' THEN SUM(POPLTN_CNT) END FEMALE_SUM
				FROM TB_POPLTN
				WHERE POPLTN_SE_CD IN ('F','M') AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
				GROUP BY ADMINIST_ZONE_NM, POPLTN_SE_CD
			  ) A
		GROUP BY ADMINIST_ZONE_NM
	 ) B;

SELECT *
FROM
	(
		SELECT ADMINIST_ZONE_NO, ADMINIST_ZONE_NM, MALE_POPLTN_CNT, FEMALE_POPLTN_CNT,
			   MALE_POPLTN_CNT / TOT_POPLTN_CNT "남성인구비율", 
			   FEMALE_POPLTN_CNT / TOT_POPLTN_CNT AS "여성인구비울", 
			   ROW_NUMBER() OVER(ORDER BY MALE_POPLTN_CNT / TOT_POPLTN_CNT) AS MALE_RATE_ASC,
			   ROW_NUMBER() OVER(ORDER BY FEMALE_POPLTN_CNT / TOT_POPLTN_CNT) AS FEMALE_RATE_ASC,
			   ROW_NUMBER() OVER(ORDER BY MALE_POPLTN_CNT / TOT_POPLTN_CNT DESC) AS MALE_RATE_DESC,
			   ROW_NUMBER() OVER(ORDER BY FEMALE_POPLTN_CNT / TOT_POPLTN_CNT DESC) AS FEMALE_RATE_DESC
		FROM
		(
			SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO, MAX(MALE_POPLTN_CNT) MALE_POPLTN_CNT, MAX(FEMALE_POPLTN_CNT) FEMALE_POPLTN_CNT, MAX(MALE_POPLTN_CNT)+MAX(FEMALE_POPLTN_CNT) AS TOT_POPLTN_CNT
			FROM
				(
					SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO,
						   CASE WHEN POPLTN_SE_CD = 'M' THEN POPLTN_CNT ELSE 0 END MALE_POPLTN_CNT,
						   CASE WHEN POPLTN_SE_CD = 'F' THEN POPLTN_CNT ELSE 0 END FEMALE_POPLTN_CNT
					FROM
						(
							SELECT ADMINIST_ZONE_NM, ADMINIST_ZONE_NO, POPLTN_SE_CD, SUM(POPLTN_CNT) AS POPLTN_CNT
							FROM TB_POPLTN
							WHERE POPLTN_SE_CD IN ('F','M') AND ADMINIST_ZONE_NO NOT LIKE '_____00000' AND POPLTN_CNT > 0
							GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM, POPLTN_SE_CD
						)A
				)B
			GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM
		)C
	)D
WHERE MALE_RATE_ASC = 1 OR FEMALE_RATE_ASC = 1 OR MALE_RATE_DESC = 1 OR FEMALE_RATE_DESC = 1
;