USE basic_query;

SELECT * FROM TB_PBTRNSP;

### 1. 승하차 구분 코드 별로 인원수가 많은 순으로 조회
SELECT *
FROM TB_PBTRNSP
WHERE STD_MT = '202304'
GROUP BY STATN_ND, STATN_NM, HO_LN, TKCAR_GFF_SE_CD;

-- 승차 및 하차 인원수가 가장 적고 가장 많은 역 조회
-- 승차 1등, 꼴등 / 하차 1등, 꼴등
SELECT *, CASE WHEN TKCAR_GFF_SE_CD = "TK" THEN '하차1등'
			   WHEN TKCAR_GFF_SE_CD = "GF" THEN '승차1등' END RNK
FROM TB_PBTRNSP
WHERE NMPR_CNT IN ( SELECT MAX(NMPR_CNT)
				   FROM TB_PBTRNSP
				   GROUP BY TKCAR_GFF_SE_CD)
UNION
SELECT *, CASE WHEN TKCAR_GFF_SE_CD = "TK" THEN '하차꼴등' 
			   WHEN TKCAR_GFF_SE_CD = "GF" THEN '승차꼴등' END RNK
FROM TB_PBTRNSP
WHERE NMPR_CNT IN ( SELECT MIN(NMPR_CNT)
				   FROM TB_PBTRNSP
                   WHERE NMPR_CNT > 0
				   GROUP BY TKCAR_GFF_SE_CD);
                   
SELECT *
FROM TB_PBTRNSP
WHERE TKCAR_GFF_SE_CD > 0;

SELECT A.STATN_NM,
	   A.TKCAR_GFF_SE_CD,
       MAX(A.GF_SUM) GF_SUM_MAX,
       MAX(A.TK_SUM) TK_SUM_MAX
FROM
	(
		SELECT STATN_NM, 
			   TKCAR_GFF_SE_CD, 
			   CASE WHEN TKCAR_GFF_SE_CD = 'GF' THEN SUM(NMPR_CNT) ELSE 0 END GF_SUM,
			   CASE WHEN TKCAR_GFF_SE_CD = 'TK' THEN SUM(NMPR_CNT) ELSE 0 END TK_SUM
		FROM TB_PBTRNSP
		GROUP BY STATN_NM, TKCAR_GFF_SE_CD
	) A
;

### 출근 시간대에 하차 인원수가 가장 많은 순으로 데이터 조회
SELECT STATN_NO, STATN_NM, HO_LN, SUM(NMPR_CNT)
FROM TB_PBTRNSP
WHERE STD_MT = '202304'
AND BEGIN_TIME = '0700'
AND END_TIME = '0800'
AND TKCAR_GFF_SE_CD = 'GF'
GROUP BY STATN_NO, STATN_NM, HO_LN
ORDER BY NMPR_CNT DESC
LIMIT 10;

## 출근 시간대에 승차를 많이하는 역
SELECT STATN_NO, STATN_NM, HO_LN, SUM(NMPR_CNT)
FROM TB_PBTRNSP
WHERE STD_MT = '202304'
AND BEGIN_TIME = '0700'
AND END_TIME = '0800'
AND TKCAR_GFF_SE_CD = 'TK'
GROUP BY STATN_NO, STATN_NM, HO_LN
ORDER BY NMPR_CNT DESC
LIMIT 10;

### 23시 이후에 사람들이 가장 많이 승차하는 역 구하기 (막차타는 사람들)
SELECT STATN_NO, STATN_NM, HO_LN, SUM(NMPR_CNT)
FROM TB_PBTRNSP
WHERE STD_MT = '202304'
AND (BEGIN_TIME, END_TIME) IN (('2300','2400'),('0000','0100'),('0100','0200'),('0200','0300'),('0300','0400')) # 동시에 만족하는 조건
AND TKCAR_GFF_SE_CD = 'TK'
GROUP BY STATN_NO, STATN_NM, HO_LN
ORDER BY NMPR_CNT DESC
LIMIT 10;

### 각 호선 별 승하차 인원수가 가장 많은 역 구하기